# About
title: Eric Stein
name: Eric Stein
email: steinea@protonmail.com
description: >-
  Garden
url: https://steinea.xyz
bluesky_username: steinea.bsky.social
github_username: steinea

# Build
plugins:
  - jekyll_custom_permalink
  - jekyll-environment-variables
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-toc

# Defaults
defaults:
  - scope:
      path: ''
      type: pages
    values:
      permalink: /:basename/
  - scope:
      path: ''
      type: posts
    values:
      permalink: /:year/:month/:day/:title/

# Exclusions
exclude:	['/_posts/commonplace/template.md',
		'/_posts/social/template.md',
		'/pages/garden/template.md',
		'/pages/inventory/_templates']